// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ['/usr/lib/slepcdir/slepc3.12/x86_64-linux-gnu-rea
//                                  l/include', '/usr/lib/petscdir/petsc3.12/x86_64-li
//                                  nux-gnu-real/include', '/usr/lib/x86_64-linux-gnu/
//                                  openmpi/include', '/usr/lib/x86_64-linux-gnu/openm
//                                  pi/include/openmpi', '/usr/include/hdf5/openmpi', 
//                                  '/usr/include/eigen3', '/usr/lib/python3/dist-pack
//                                  ages/ffc/backends/ufc']
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              None
//  quadrature_rule:                None
//  representation:                 'auto'
//  split:                          False

#ifndef __FFC_FORM_F8BE833CAFE634B6E0490C44A4A1328079268831_H
#define __FFC_FORM_F8BE833CAFE634B6E0490C44A4A1328079268831_H
#include "ffc_coordinate_mapping_74de9105f381ea74dcd14a046879d17a815aece6.h"
#include "ffc_element_2bc572a872970471903740642e8195b32ad2fc36.h"
#include "ffc_element_3893c563eb9a59518bdaca7d6bbcd4f13320b65c.h"
#include "ffc_element_cea84afbb5a50c73ab8d3e35f2472dc16cf8ab24.h"
#include "ffc_element_fd1fb0e6bb5707e8dd40df830c02a772bdead3c7.h"
#include <algorithm>
#include <cmath>
#include <iostream>
#include <stdexcept>
#include <ufc.h>

class ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_cell_integral_main_otherwise: public ufc::cell_integral
{
public:

  ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_cell_integral_main_otherwise();

  ~ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_cell_integral_main_otherwise() override;

  const std::vector<bool> & enabled_coefficients() const final override;

  void tabulate_tensor(double * A,
                       const double * const * w,
                       const double * coordinate_dofs,
                       int cell_orientation,
                       std::size_t local_facet) const final override;

};

extern "C" ufc::cell_integral * create_ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_cell_integral_main_otherwise();


class ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_exterior_facet_integral_main_otherwise: public ufc::exterior_facet_integral
{
public:

  ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_exterior_facet_integral_main_otherwise();

  ~ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_exterior_facet_integral_main_otherwise() override;

  const std::vector<bool> & enabled_coefficients() const final override;

  void tabulate_tensor(double * A,
                       const double * const * w,
                       const double * coordinate_dofs,
                       std::size_t facet,
                       int cell_orientation) const final override;

};

extern "C" ufc::exterior_facet_integral * create_ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_exterior_facet_integral_main_otherwise();


class ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_form_main: public ufc::form
{
public:

  ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_form_main();

  ~ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_form_main() override;

  const char * signature() const final override;

  std::size_t rank() const final override;

  std::size_t num_coefficients() const final override;

  std::size_t original_coefficient_position(std::size_t i) const final override;

  ufc::finite_element * create_coordinate_finite_element() const final override;

  ufc::dofmap * create_coordinate_dofmap() const final override;

  ufc::coordinate_mapping * create_coordinate_mapping() const final override;

  ufc::finite_element * create_finite_element(std::size_t i) const final override;

  ufc::dofmap * create_dofmap(std::size_t i) const final override;

  std::size_t max_cell_subdomain_id() const final override;

  std::size_t max_exterior_facet_subdomain_id() const final override;

  std::size_t max_interior_facet_subdomain_id() const final override;

  std::size_t max_vertex_subdomain_id() const final override;

  std::size_t max_custom_subdomain_id() const final override;

  std::size_t max_cutcell_subdomain_id() const final override;

  std::size_t max_interface_subdomain_id() const final override;

  std::size_t max_overlap_subdomain_id() const final override;

  bool has_cell_integrals() const final override;

  bool has_exterior_facet_integrals() const final override;

  bool has_interior_facet_integrals() const final override;

  bool has_vertex_integrals() const final override;

  bool has_custom_integrals() const final override;

  bool has_cutcell_integrals() const final override;

  bool has_interface_integrals() const final override;

  bool has_overlap_integrals() const final override;

  ufc::cell_integral * create_cell_integral(std::size_t i) const final override;

  ufc::exterior_facet_integral * create_exterior_facet_integral(std::size_t i) const final override;

  ufc::interior_facet_integral * create_interior_facet_integral(std::size_t i) const final override;

  ufc::vertex_integral * create_vertex_integral(std::size_t i) const final override;

  ufc::custom_integral * create_custom_integral(std::size_t i) const final override;

  ufc::cutcell_integral * create_cutcell_integral(std::size_t i) const final override;

  ufc::interface_integral * create_interface_integral(std::size_t i) const final override;

  ufc::overlap_integral * create_overlap_integral(std::size_t i) const final override;

  ufc::cell_integral * create_default_cell_integral() const final override;

  ufc::exterior_facet_integral * create_default_exterior_facet_integral() const final override;

  ufc::interior_facet_integral * create_default_interior_facet_integral() const final override;

  ufc::vertex_integral * create_default_vertex_integral() const final override;

  ufc::custom_integral * create_default_custom_integral() const final override;

  ufc::cutcell_integral * create_default_cutcell_integral() const final override;

  ufc::interface_integral * create_default_interface_integral() const final override;

  ufc::overlap_integral * create_default_overlap_integral() const final override;

};

extern "C" ufc::form * create_ffc_form_f8be833cafe634b6e0490c44a4a1328079268831_form_main();

#endif
